# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-10-05 08:11
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-timestamp', '-updated']},
        ),
        migrations.AddField(
            model_name='blog',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=blog.models.upload_location, width_field='width_field'),
        ),
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default='qwer'),
        ),
        migrations.AddField(
            model_name='blog',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
    ]
